/**
 * Client/src/screens/DebugScreen.js
 * 
 * Production-quality Debug Screen.
 * Renders a terminal-like console window detailing real-time SIP.js transactions,
 * Socket connections, and WebRTC renegotiation logs.
 * Supports keyword search, username filters, and log cleaning.
 */

import React, { useState, useEffect, useMemo } from 'react';
import {
  SafeAreaView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  FlatList,
  StatusBar,
  Platform,
} from 'react-native';
import Logger from '../services/Logger';
import Icon from 'react-native-vector-icons/Ionicons';

const FILTER_USERS = ['All', 'Alice', 'Bob', 'Charlie', 'David', 'Emily', 'Jack', 'System'];

export default function DebugScreen({ navigation }) {
  const [logs, setLogs] = useState([]);
  const [search, setSearch] = useState('');
  const [selectedUser, setSelectedUser] = useState('All');

  // Subscribe to real-time logs generated by Logger.js
  useEffect(() => {
    // Sync initial logs
    setLogs([...Logger.getLogs()]);

    const unsubscribe = Logger.subscribe(() => {
      // Refresh state from logger records
      setLogs([...Logger.getLogs()]);
    });

    return () => unsubscribe();
  }, []);

  const handleClear = () => {
    Logger.clearLogs();
  };

  // Filter logs based on search phrase and selected user badge
  const filteredLogs = useMemo(() => {
    return logs.filter((log) => {
      const matchUser =
        selectedUser === 'All' ||
        log.username.toLowerCase() === selectedUser.toLowerCase();
      
      const searchLower = search.toLowerCase();
      const matchSearch =
        !search.trim() ||
        log.action.toLowerCase().includes(searchLower) ||
        log.module.toLowerCase().includes(searchLower) ||
        log.method.toLowerCase().includes(searchLower) ||
        log.result.toLowerCase().includes(searchLower);

      return matchUser && matchSearch;
    });
  }, [logs, search, selectedUser]);

  const renderLogCard = ({ item }) => {
    // Resolve user tag colors
    const getUserTagStyle = (username) => {
      if (username === 'System') return styles.systemUserTag;
      return styles.activeUserTag;
    };

    return (
      <View style={styles.logCard}>
        <View style={styles.logHeader}>
          <Text style={styles.logTime}>[{item.timestamp}]</Text>
          <View style={[styles.userTag, getUserTagStyle(item.username)]}>
            <Text style={styles.userTagText}>{item.username}</Text>
          </View>
        </View>

        <View style={styles.logMetaRow}>
          <Text style={styles.logMetaLabel}>Module:</Text>
          <Text style={styles.logMetaVal}>{item.module}</Text>
          <Text style={styles.logMetaDivider}>|</Text>
          <Text style={styles.logMetaLabel}>Method:</Text>
          <Text style={styles.logMetaVal}>{item.method}</Text>
        </View>

        <Text style={styles.logActionText}>{item.action}</Text>
        
        {item.result ? (
          <Text style={styles.logResultText} numberOfLines={3}>
            Result: {item.result}
          </Text>
        ) : null}
      </View>
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#0B0F19" />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
            <Icon name="arrow-back" size={14} color="#38BDF8" />
            <Text style={styles.backBtnText}>Back</Text>
          </View>
        </TouchableOpacity>
        <Text style={styles.title}>Console Logs</Text>
        <TouchableOpacity style={styles.clearBtn} onPress={handleClear}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
            <Icon name="trash-outline" size={14} color="#FECACA" />
            <Text style={styles.clearBtnText}>Clear</Text>
          </View>
        </TouchableOpacity>
      </View>

      {/* Search Console */}
      <View style={styles.searchContainer}>
        <TextInput
          style={styles.searchInput}
          placeholder="Search logs (e.g., SIP, Offer)..."
          placeholderTextColor="#475569"
          value={search}
          onChangeText={setSearch}
          autoCapitalize="none"
          autoCorrect={false}
        />
      </View>

      {/* User Badges Selector */}
      <View style={styles.badgesWrapper}>
        <ScrollViewHorizontal horizontal showsHorizontalScrollIndicator={false} style={styles.badgesScroll}>
          {FILTER_USERS.map((user) => (
            <TouchableOpacity
              key={user}
              style={[
                styles.userBadge,
                selectedUser === user && styles.userBadgeActive,
              ]}
              onPress={() => setSelectedUser(user)}
            >
              <Text
                style={[
                  styles.userBadgeText,
                  selectedUser === user && styles.userBadgeTextActive,
                ]}
              >
                {user}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollViewHorizontal>
      </View>

      {/* Logs Terminal Area */}
      <FlatList
        data={filteredLogs}
        keyExtractor={(item) => item.id}
        renderItem={renderLogCard}
        contentContainerStyle={styles.listContent}
        ListEmptyComponent={
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>Console is empty. Actions will stream here.</Text>
          </View>
        }
      />
    </SafeAreaView>
  );
}

// Custom horizontal ScrollView for badge row (simulating ScrollView horizontal in pure elements)
const ScrollViewHorizontal = ({ children, style, ...props }) => {
  return (
    <View style={styles.badgesWrapperContainer}>
      <FlatList
        horizontal
        showsHorizontalScrollIndicator={false}
        data={React.Children.toArray(children)}
        keyExtractor={(_, index) => index.toString()}
        renderItem={({ item }) => item}
        contentContainerStyle={styles.badgesScrollContent}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#020617', // Terminal dark slate 950
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
    backgroundColor: '#0F172A',
  },
  backBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#1E293B',
    borderRadius: 6,
  },
  backBtnText: {
    color: '#38BDF8',
    fontWeight: '600',
    fontSize: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: '800',
    color: '#38BDF8',
  },
  clearBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#7F1D1D',
    borderRadius: 6,
  },
  clearBtnText: {
    color: '#FECACA',
    fontWeight: '600',
    fontSize: 12,
  },
  searchContainer: {
    paddingHorizontal: 16,
    marginTop: 12,
  },
  searchInput: {
    backgroundColor: '#0F172A',
    borderColor: '#1E293B',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#F8FAFC',
    fontSize: 14,
  },
  badgesWrapper: {
    height: 48,
    marginTop: 8,
  },
  badgesWrapperContainer: {
    flex: 1,
  },
  badgesScrollContent: {
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 8,
  },
  userBadge: {
    backgroundColor: '#0F172A',
    borderColor: '#1E293B',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  userBadgeActive: {
    backgroundColor: '#0EA5E9',
    borderColor: '#0EA5E9',
  },
  userBadgeText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  userBadgeTextActive: {
    color: '#FFFFFF',
  },
  listContent: {
    padding: 16,
  },
  logCard: {
    backgroundColor: '#0F172A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#38BDF8',
  },
  logHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  logTime: {
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    color: '#38BDF8',
    fontWeight: '600',
  },
  userTag: {
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  activeUserTag: {
    backgroundColor: '#1E293B',
  },
  systemUserTag: {
    backgroundColor: '#7F1D1D',
  },
  userTagText: {
    color: '#94A3B8',
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  logMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  logMetaLabel: {
    fontSize: 10,
    color: '#475569',
    fontWeight: '600',
  },
  logMetaVal: {
    fontSize: 10,
    color: '#94A3B8',
    fontWeight: '600',
    marginLeft: 3,
  },
  logMetaDivider: {
    marginHorizontal: 6,
    color: '#1E293B',
    fontSize: 10,
  },
  logActionText: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  logResultText: {
    color: '#94A3B8',
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    backgroundColor: '#020617',
    padding: 6,
    borderRadius: 4,
    marginTop: 4,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 100,
  },
  emptyText: {
    color: '#475569',
    fontSize: 14,
    textAlign: 'center',
  },
});
